### PR TITLE
Fix clock face rounding

### PR DESCRIPTION
**Pull request by brandl-muc**
Note that this PR also contains the refactoring of #50. Review is certainly easier after that PR was completed.

Basically I moved rounding to its own function which is now used for vulgar fraction and Unicode clock faces.
This fixes issue #32 .

### CODE REVIEW

**Comment by brandl-muc** [comment]
I might also rebase these changes onto master once PR #50 was merged.

**Comment by brandl-muc** [comment]
Changes were rebased onto master and force pushed, now review is possible.

**Comment by da2x** [comment]
Thanks! I’ll find some time to do another release soonish. Feel free to poke me in a few weeks if I forget.

**Comment by brandl-muc** [comment]
I have some spare time this week, can't promise anything, but maybe it's worth the wait. :wink:

**Pull request merged**
