### PR TITLE
Add basic arithmetic operation support with code %;A()

### PR DESCRIPTION
**Pull request by Techser**
Add arithmetic operations with code %;A(), for example %;A(10000 + %Y)

### CODE REVIEW

**Comment by da2x** [comment]
Thank you for your pull request.

Could you please explain when this functionality is useful? I'm having trouble finding a usecase for it.

**Comment by Techser** [comment]
I added it to enable conversion between units, right now I'm using it to turn the current years into the current Holocene year

**Comment by da2x** [comment]
Wouldn’t `1%Y` output the Holocene calendar year (at least for the next 7979,8 years)?

**Comment by Techser** [comment]
Yes that would work, but it just felt better to add 10,000. I was thinking this could be used to convert to non-standard units of time, but honestly this was probably just a case of me implementing functionality because I could.

**Pull request closed without merging**
